---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown


### content configuration ###
title:       "ViperDev Nikolaus Pitch"
keywords:    "Pitch, nonprofit, social, sozial, impact, Gesellschaft"
description: "Brauchst du Softwareentwickler*innen um deine Idee zu realisieren? Soziale Unternehmungen können sich mit einer App-Idee bis zum 30. November 2018 bewerben."
source_link: "https://nikolauspitch.de/"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key:


### template colors, used site-wide via css ###
colors:
  black:     '#111111'
  white:     '#f8f8f8'
  blue:      '#201b54'
  green:     '#9bcf2f'
  purple:    '#c869bf'
  orange:    '#fab125'
  turquoise: '#0fbfcf'

kramdown:
  auto_ids:  false
